<Project Sdk="Godot.NET.Sdk/4.5.1">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>true</ImplicitUsings>
    <LangVersion>12.0</LangVersion>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>BigDogMod</RootNamespace>
    <AssemblyName>BigDogMod</AssemblyName>
    <Sts2Dir>D:\steam\steamapps\common\Slay the Spire 2</Sts2Dir>
    <Sts2DataDir>$(Sts2Dir)\data_sts2_windows_x86_64</Sts2DataDir>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="sts2">
      <HintPath>$(Sts2DataDir)\sts2.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="0Harmony">
      <HintPath>$(Sts2DataDir)\0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="BaseLib">
      <HintPath>ThirdParty\BaseLib\BaseLib.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="STS2-RitsuLib">
      <HintPath>ThirdParty\RitsuLib\STS2-RitsuLib.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="ThirdParty\BaseLibSource\**\*.cs" />
    <EmbeddedResource Remove="ThirdParty\BaseLibSource\**\*" />
    <None Remove="ThirdParty\BaseLibSource\**\*" />
    <Compile Remove="ThirdParty\RitsuLibSource\**\*.cs" />
    <EmbeddedResource Remove="ThirdParty\RitsuLibSource\**\*" />
    <None Remove="ThirdParty\RitsuLibSource\**\*" />
  </ItemGroup>

  <Target Name="Copy Mod" AfterTargets="PostBuildEvent">
    <Message Text="Copying mod to Slay the Spire 2 mods folder..." Importance="high" />
    <MakeDir Directories="$(Sts2Dir)\mods\$(MSBuildProjectName)\" />
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(Sts2Dir)\mods\$(MSBuildProjectName)\" />
    <Copy SourceFiles="$(MSBuildProjectName).json" DestinationFolder="$(Sts2Dir)\mods\$(MSBuildProjectName)\" />
  </Target>
</Project>
